#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation


userBundle-index:
    path: /
    defaults: { _controller: JbpUserBundle:Default:index }

userBundle-register:
    path: /reg
    defaults: { _controller: JbpUserBundle:Default:register }

userBundle-login:
    path: /login
    defaults: { _controller: JbpUserBundle:Default:login }

userBundle-logout:
    path: /logout
    defaults: { _controller: JbpUserBundle:Default:logout }

userBundle-api-register:
    path: /api/reg
    defaults: { _controller: JbpUserBundle:Api:mobileRegister }
#
#userBundle-register:
#    path: /reg
#    defaults: { _controller: JbpUserBundle:Default:register }
#
#userBundle-login:
#    path: /login
#    defaults: { _controller: JbpUserBundle:Default:login }
#
#userBundle-logout:
#    path: /logout
#    defaults: { _controller: JbpUserBundle:Default:logout }