# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
#security:
#    encoders:
#        JbpUserBundle\Entity\User: bcrypt
#    providers:
#        main:
#            entity: { class: JbpUserBundle:Entity:User, property: name }
#    firewalls:
#        main:
#            pattern: /.*
#            form_login:
#                check_path: /login_check
#                login_path: /login
#                default_target_path: /index
#            logout: true
#            security: true
#            anonymous: true
#    access_control:
#        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /.*, role: ROLE_ADMIN }

security:
    # ...

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check