security:
    encoders:
<<<<<<< HEAD
        Symfony\Component\Security\Core\User\User:    plaintext
        Jbp\Bundle\UserBundle\Entity\JukuUser:        plaintext

    providers:
        main:
            entity:
                class: Jbp\Bundle\UserBundle\Entity\JukuUser
                property: username

        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

=======
        Symfony\Component\Security\Core\User\User:                      plaintext

    providers:
        default:
            entity:
                class: Jbp\Bundle\UserBundle\Entity\JukuUser
                property: username

        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

>>>>>>> f60832038a874a1ed70371b062a904c2f42f68d5
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #安全设置跳过登录页
        login:
<<<<<<< HEAD
            pattern:  ^/user/(login|reg)$
=======
            pattern:  ^/user/login$
>>>>>>> f60832038a874a1ed70371b062a904c2f42f68d5
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: jbp_user_login_check
                login_path: jbp_user_login
                default_target_path: jbp_user_index
                #csrf_token_generator: security.csrf.token_manager

            logout:
                path:   jbp_user_logout
                target: jbp_user_login

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        - { path: ^/user/logout$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
<<<<<<< HEAD
=======

>>>>>>> f60832038a874a1ed70371b062a904c2f42f68d5
