imports:
    - { resource: "../../config/common_parameters.yml" }
    - { resource: parameters.yml }
    - { resource: "../../config/common_config.yml" }
    - { resource: security.yml }
    - { resource: services.yml }

services:
    twig.extension.debug:
        class: Twig_Extension_Debug
        tags:
            - { name: twig.extension }
monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false

authbucket_oauth2:
    driver:                 orm
    user_provider:          security.user.provider.concrete.default
    model:
        access_token:       AuthBucket\Bundle\OAuth2Bundle\Entity\AccessToken
        authorize:          AuthBucket\Bundle\OAuth2Bundle\Entity\Authorize
        client:             AuthBucket\Bundle\OAuth2Bundle\Entity\Client
        code:               AuthBucket\Bundle\OAuth2Bundle\Entity\Code
        refresh_token:      AuthBucket\Bundle\OAuth2Bundle\Entity\RefreshToken
        scope:              AuthBucket\Bundle\OAuth2Bundle\Entity\Scope
        user:               AuthBucket\Bundle\OAuth2Bundle\Entity\User
