security:
    encoders:
        Authbucket\Bundle\OAuth2Bundle\Tests\TestBundle\Entity\User:    plaintext
        Symfony\Component\Security\Core\User\User:                      plaintext

    providers:
        default:
            entity:
                class: Jbp\Bundle\UserBundle\Entity\JukuUser
                property: username

        admin:
            memory:
                users:
                    admin:          { roles: 'ROLE_ADMIN', password: secrete }

    firewalls:
        api_oauth2_authorize:
            pattern:                ^/api/oauth2/authorize$
            http_basic:             ~
            provider:               admin

        api_oauth2_token:
            pattern:                ^/api/oauth2/token$
            oauth2_token:           ~

        api_oauth2_debug:
            pattern:                ^/api/oauth2/debug$
            oauth2_resource:        ~

        api_resource_model:
            pattern:                ^/api/resource/model$
            oauth2_resource:
                resource_type:      model
                scope:              [ demoscope1 ]

        api_resource_debug_endpoint:
            pattern:                ^/api/resource/debug_endpoint$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    debug_endpoint: '/api/oauth2/debug'
                    cache:          false

        api_resource_debug_endpoint_cache:
            pattern:                ^/api/resource/debug_endpoint/cache$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    debug_endpoint: '/api/oauth2/debug'
                    cache:          true

        api_resource_debug_endpoint_invalid_options:
            pattern:                ^/api/resource/debug_endpoint/invalid_options$
            oauth2_resource:
                resource_type:      debug_endpoint
                scope:              [ demoscope1 ]
                options:
                    debug_endpoint: ''
                    cache:          true
