# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    user_service:
        class:        Jbp\Bundle\UserBundle\Service\JbpUserService
        arguments:    []
    userProfile_service:
        class:        Jbp\Bundle\UserBundle\Service\JbpUserProfileService
        arguments:    []
    userAccount_service:
        class:        Jbp\Bundle\UserBundle\Service\JbpUserAccountService
        arguments:    []
