Jbp\Bundle\UserBundle\Entity\JukuUserAccount:
    type: entity
    table: juku_user_account
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: bigint
            nullable: false
            options:
                unsigned: true
            column: user_id
        point:
            type: integer
            nullable: false
            options:
                unsigned: true
                comment: 积分
                default: '0'
        userType:
            type: boolean
            nullable: false
            options:
                comment: 用户类型
                default: '0'
            column: user_type
        allowWithdraw:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 可提现余额/可提现佣金
                default: '0.00'
            column: allow_withdraw
        allIncome:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 累计收益
                default: '0.00'
            column: all_income
        pendingCommission:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 待结算佣金
                default: '0.00'
            column: pending_commission
        balance:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 我的余额
                default: '0.00'
        saleAmount:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 总销售额
                default: '0.00'
            column: sale_amount
        totalWithdraw:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 累计提现
                default: '0.00'
            column: total_withdraw
        frozenCapital:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 冻结资金
                default: '0.00'
            column: frozen_capital
        unexpenditureCommission:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 未支出分润
                default: '0.00'
            column: unexpenditure_commission
        expenditureCommission:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 已支出分润
                default: '0.00'
            column: expenditure_commission
        shopId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: 店铺ID
            column: shop_id
        shareholder:
            type: decimal
            nullable: false
            precision: 7
            scale: 2
            options:
                comment: 入股余额
                default: '0.00'
    lifecycleCallbacks: {  }
