Jbp\Bundle\UserBundle\Entity\JukuUserNav:
    type: entity
    table: juku_user_nav
    id:
        id:
            type: bigint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        shopId:
            type: bigint
            nullable: false
            options:
                unsigned: true
                comment: ' 用户 ID'
            column: shop_id
        data:
            type: text
            nullable: true
            length: 65535
            options:
                fixed: false
                comment: 导航数据，JSON
    lifecycleCallbacks: {  }
